services:
  sql-server-db:
    container_name: BSMNT-server-db
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "BSMNT_Web123!"
      ACCEPT_EULA: "Y"
